apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: frontend-golden-path
  name: frontend-golden-path
  namespace: frontend-golden-path

spec:
  ingresses:
    - https://frontend-golden-path.intern.dev.nav.no
    - https://roger.com
  image: {{image}}
  port: 3000
  prometheus:
    enabled: true
    path: "/api/metrics"
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
  accessPolicy:
    outbound:
      rules:
        - application: frontend-golden-path-api
        - application: nav-dekoratoren
          namespace: personbruker
  tokenx:
    enabled: true
